Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -6,10 +6,7 @@
 name: Houston Service - CICD Workflow
 
 on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+  push
 
 jobs:
   build:
@@ -17,10 +14,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Extract current branch name
+      shell: bash
+      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+      id: extract_branch
+    - name: Echo Branch Name
+      shell: bash
+      run: |
+        echo Branch name: ${{ steps.extract_branch.outputs.branch }}      
     - uses: actions/checkout@v2
       with:
         repository: tranquilitybase-io/tb-houston-service
-        path: tb-houston-service
+        path: .
+        fetch-depth: 0
     - name: Set up Python 3.6
       uses: actions/setup-python@v1
       with:
@@ -28,9 +34,6 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        env
-        cd ${GITHUB_WORKSPACE}/tb-houston-service
-        ls -alrt
         pip install -r requirements.txt
     - name: Lint with flake8
       run: |
@@ -45,3 +48,29 @@ jobs:
         cd ${GITHUB_WORKSPACE}/tb-houston-service/tests
         # No tests at the moment
         #pytest tests/
+    - name: run semver, store in step variable version
+      shell: bash
+      run: |
+        echo "##[set-output name=version;]$(python scripts/semver.py ${{ steps.extract_branch.outputs.branch }})"
+      id: get_version
+    - name: check if version variable is set
+      shell: bash
+      run: |
+        if [[ -z ${{ steps.get_version.outputs.version }} ]]; then
+          echo "Error: version in environment is not set." 1>&2
+          exit 1
+        fi
+        cat version.json
+    - name: git add, commit and push
+      shell: bash
+      run: |
+        git config user.email git.action@gft.com
+        git config user.name "git.action"
+        git add version.json
+        git commit -m "Add version.json"
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: ${{ steps.extract_branch.outputs.branch }}
+        force: true
+        github_token: ${{ secrets.GITHUB_TOKEN }}                      
